search_project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import SignUpView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'accounts'

urlpatterns = [
    path('signup', SignUpView.as_view(), name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='accounts:login'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_project/search_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_runserver(request):
    return redirect('accounts:login')

urlpatterns = [
    path('', redirect_to_runserver),
    path('admin/', admin.site.urls),
    path('mycollection/', include('mycollection.urls')),
    path('search/', include('search_app.urls')),
    path('', include('accounts.urls')),
]

search_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    email = models.EmailField('メールアドレス', unique=True)
# Create your models here.

search_project/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )

class LoginForm(AuthenticationForm):
    pass

search_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy
from django.views import View
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required

class SignUpView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'signup.html', {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('mycollection:home')
        return render(request, 'signup.html', {'form': form})

search_project/accounts/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ログイン画面</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/collog_favicon.ico' %}">
        <!-- Apple ホームアイコン -->
        <link rel="apple-touch-icon" sizes="180x180"  href="{% static 'images/collog.png' %}" />
        <!-- Android ホームアイコン -->
        <link rel="icon" type="image/png" sizes="192x192" href="{% static 'images/collog.png' %}">
    </head>
    <body>
        <div class="glass-container">
            <div class="login-box">
                <div class="app-logo">
                    <img src="{% static 'images/collog.png' %}" alt="アプリロゴ">
                </div>
                <h2>ログイン</h2>
                <form method="POST">
                    {% csrf_token %}
                    <div class="error-message">
                    {% if form.errors %}
                        <div class="alert alert-danger" style="margin-top: 10px;">
                            <ul>
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    </div>
                    <input type="text" id="username" name="username" required placeholder="名前">
                    <input type="password" id="password" name="password" required placeholder="パスワード">
                    <div class="options">
                        <!-- <input type="checkbox" id="remember" name="remember" checked>
                        <label for="remember">Recordarme</label> -->
                        <!-- <a href="#">Forgot Password?</a> -->
                    </div>
                    <button type="submit">ログイン</button>
                    <div class="sign-up-a">
                        <a href="{% url 'accounts:signup' %}">サインアップの方はこちら</a>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>
<style>
    * {
    margin: 0;
    box-sizing: border-box;
    font-family: 'montserrat', Arial, Helvetica, sans-serif;
}
body {
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-image: url('../static/images/image.jpg');
    background-size: cover;
}
.glass-container{
    width: 300px;
    height: auto;
    position: relative;
    z-index: 1;
    background: rgba(255, 255, 255, 0.1);
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    border-radius: 10px;
    border: 1px solid #fff;
}
.glass-container::before {
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 10px;
    backdrop-filter: blur(5px);
    -webkit-backdrop-filter: blur(5px);
    z-index: -1;
}
.login-box{
    max-width: 250px;
    margin: 0 auto;
    text-align: center;
}
.app-logo {
    margin : 30px 0 20px 0;
}
.app-logo img {
    width: 100px;
    height: 100px;
}
h2{
    color: #fff;
}
form{
    display: flex;
    flex-direction: column;
}
input{
    padding: 10px;
    margin-top: 25px;
    border: none;
    border-radius: 10px;
    background: transparent;
    border: 1px solid #fff;
    color: #fff;
    font-size: 13px;
}
input::placeholder{
    color: #fff;
}
input:focus{
    outline: none;
}
.options{
    display: flex;
    align-items: center;
    margin-top: 15px;
    font-size: 12px;
    color: white;
}
.options input{
    margin-right: 5px;
    margin-top: 0px;
}
.options a{
    text-decoration: none;
    color: white;
    margin-left: auto;
}
button{
    background: #fff;
    color: black;
    padding: 10px;
    border: none;
    border-radius: 10px;
    cursor: pointer;
    margin-top: 15px;
}
button:hover{
    background: transparent;
    color: white;
    outline: 1px solid #fff;
}
p{
    font-size: 12px;
    color: #fff;
    margin-top: 15px;
}
.sign-up-a {
    font-size: 12px;
    margin: 15px 0 30px 0;
}
</style>

search_project/accounts/templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>サインアップ画面</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/collog_favicon.ico' %}">
        <!-- Apple ホームアイコン -->
        <link rel="apple-touch-icon" sizes="180x180"  href="{% static 'images/collog.png' %}" />
        <!-- Android ホームアイコン -->
        <link rel="icon" type="image/png" sizes="192x192" href="{% static 'images/collog.png' %}">
    </head>
    <body>
        <div class="glass-container">
            <div class="login-box">
                <div class="app-logo">
                    <img src="{% static 'images/collog.png' %}" alt="アプリロゴ">
                </div>
                <h2>サインアップ</h2>
                <form method="POST">
                    {% csrf_token %}
                    <div class="error-message">
                    {% if form.errors %}
                        <div class="alert alert-danger" style="margin-top: 10px;">
                            <ul>
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    </div>
                    <input type="text" id="username" name="username" required placeholder="名前">
                    <input type="email" id="email" name="email" required placeholder="メールアドレス">
                    <input type="password" id="password1" name="password1" required placeholder="パスワード">
                    <input type="password" id="password2" name="password2" required placeholder="パスワード(確認用)">
                    <div class="options"></div>
                    <button type="submit">サインアップ</button>
                    <div class="login-a">
                        <a href="{% url 'accounts:login' %}">アカウントをお持ちの方はこちら</a>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>
<style>
    * {
    margin: 0;
    box-sizing: border-box;
    font-family: 'montserrat', Arial, Helvetica, sans-serif;
}
body {
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-image: url('../static/images/image1.jpg');
    background-size: cover;
}
.glass-container{
    width: 300px;
    height: auto;
    position: relative;
    z-index: 1;
    background: rgba(255, 255, 255, 0.1);
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    border-radius: 10px;
    border: 1px solid #fff;
}
.glass-container::before {
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 10px;
    backdrop-filter: blur(5px);
    -webkit-backdrop-filter: blur(5px);
    z-index: -1;
}
.login-box{
    max-width: 250px;
    margin: 0 auto;
    text-align: center;
}
.app-logo {
    margin : 30px 0 20px 0;
}
.app-logo img {
    width: 100px;
    height: 100px;
}
h2{
    color: #fff;
}
form{
    display: flex;
    flex-direction: column;
}
input{
    padding: 10px;
    margin-top: 25px;
    border: none;
    border-radius: 10px;
    background: transparent;
    border: 1px solid #fff;
    color: #fff;
    font-size: 13px;
}
input::placeholder{
    color: #fff;
}
input:focus{
    outline: none;
}
.options{
    display: flex;
    align-items: center;
    margin-top: 15px;
    font-size: 12px;
    color: white;
}
.options input{
    margin-right: 5px;
    margin-top: 0px;
}
.options a{
    text-decoration: none;
    color: white;
    margin-left: auto;
}
button{
    background: #fff;
    color: black;
    padding: 10px;
    border: none;
    border-radius: 10px;
    cursor: pointer;
    margin-top: 15px;
}
button:hover{
    background: transparent;
    color: white;
    outline: 1px solid #fff;
}
p{
    font-size: 12px;
    color: #fff;
    margin-top: 15px;
}
.login-a {
    font-size: 12px;
    margin: 15px 0 30px 0;
}
</style>