search_project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import SignUpView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'accounts'

urlpatterns = [
    path('signup', SignUpView.as_view(), name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='accounts:login'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_project/my_collection/urls.py
from django.urls import path
from . import views

app_name = 'my_collection'

urlpatterns = [
    path('home/', views.collection_home, name='home'),
]

search_project/mycollection/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'mycollection'

urlpatterns = [
    path('home', views.collection_home, name='home'),
    path('register', views.collection_register, name='collection_register'),
    path('edit/<int:pk>', views.collection_edit, name='collection_edit'),
    path('delete/<int:pk>', views.collection_delete, name='collection_delete'),
    path('category/register', views.collection_category_register, name='collection_category_register'),
    path('tag/register', views.collection_tag_register, name='collection_tag_register'),
    path('favorites', views.collection_favorites, name='collection_favorites'),
    path('add_favorite', views.collection_add_favorite, name='collection_add_favorite'),
    path('remove_favorite', views.collection_remove_favorite, name='collection_remove_favorite'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_project/search_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_runserver(request):
    return redirect('accounts:login')

urlpatterns = [
    path('', redirect_to_runserver),
    path('admin/', admin.site.urls),
    path('mycollection/', include('mycollection.urls')),
    path('search/', include('search_app.urls')),
    path('', include('accounts.urls')),
]

search_project/mycollection/models.py
from django.db import models
from accounts.models import CustomUser

class CollectionCategory(models.Model):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default="")
    def __str__(self):
        return self.name

class CollectionTag(models.Model):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default="")
    color_code = models.CharField(max_length=7)
    def __str__(self):
        return self.name

class MyCollection(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(blank=True, null=True)
    get_date = models.DateField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    collection_category = models.ForeignKey(
        CollectionCategory,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None
    )
    image_path = models.ImageField(upload_to='mycollections/')
    tag = models.ManyToManyField(CollectionTag, blank=True)
    memo = models.TextField(blank=True, null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

class CollectionFavorite(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    mycollection = models.ForeignKey(MyCollection, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name
    class Meta:
        unique_together = ('user', 'mycollection')

search_project/mycollection/forms.py
from django import forms
from .models import MyCollection , CollectionCategory , CollectionTag , CollectionFavorite

class CollectionSearchForm(forms.Form):
    collection_category = forms.ModelChoiceField(
        queryset=CollectionCategory.objects.none(),
        empty_label="分類なし",
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields['collection_category'].queryset = CollectionCategory.objects.filter(user=user)
class MyCollectionForm(forms.ModelForm):
    collection_category = forms.ModelChoiceField(
        queryset=CollectionCategory.objects.none(),
        empty_label="分類なし",
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'コレクション名'})
    )
    image_path = forms.FileField(
        required=True,
        widget=forms.FileInput(attrs={'class': 'form-control'})
    )
    tag = forms.ModelMultipleChoiceField(
        queryset=CollectionTag.objects.none(),
        required=False,
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'tag-checkbox-group'})
    )
    # ユーザーが登録したカテゴ・タグが表示されるようにする
    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields['collection_category'].queryset = CollectionCategory.objects.filter(user=user)
            self.fields['tag'].queryset = CollectionTag.objects.filter(user=user)
    class Meta:
        model = MyCollection
        fields = (
            'name',
            'description',
            'get_date',
            'price',
            'collection_category',
            'image_path',
            'tag',
            'memo',
        )
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'コレクション説明（詳細情報）'}),
            'get_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '価格', 'min': 0}),
            'memo': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'メモ'})
        }


class CollectionCategoryForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'カテゴリ名'})
    )
    class Meta:
        model = CollectionCategory
        fields = (
            'name',
        )

class CollectionTagForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'タグ名'})
    )
    color_code = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'type': 'color', 'class': 'form-control form-control-color'}),
    )
    class Meta:
        model = CollectionTag
        fields = (
            'name',
            'color_code',
        )

class CollectionFavoriteForm(forms.ModelForm):
    class Meta:
        model = CollectionFavorite
        fields = (
            'mycollection',
        )

search_project/my_collection/views.py
from django.shortcuts import render

def collection_home(request):
    return render(request, 'home.html')

search_project/mycollection/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CollectionSearchForm, MyCollectionForm, CollectionCategoryForm, CollectionTagForm, CollectionFavoriteForm
from django.contrib import messages
from .models import MyCollection , CollectionFavorite
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import io
from PIL import Image
from pillow_heif import open_heif
from django.core.files.uploadedfile import InMemoryUploadedFile

@login_required
def collection_home(request):
    mycollections = MyCollection.objects.order_by('-created_at').filter(user=request.user)

    # コレクション名検索
    query = request.GET.get('query')
    if query:
        mycollections = mycollections.filter(name__icontains=query)

    # 絞り込み検索
    form = CollectionSearchForm(user=request.user, data=request.GET)
    if form.is_valid():
        category = form.cleaned_data.get('collection_category')
        if category:
            mycollections = mycollections.filter(collection_category=category)

    get_date = request.GET.get('get_date')
    if get_date:
        mycollections = mycollections.filter(get_date__exact=get_date)

    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')
    if price_min and price_max:
        mycollections = mycollections.filter(price__gte=price_min, price__lte=price_max)
    elif price_min:
        mycollections = mycollections.filter(price__gte=price_min)
    elif price_max:
        mycollections = mycollections.filter(price__lte=price_max)

    # 並び替え順
    order = request.GET.get('order')
    if order == 'name_order':
        mycollections = mycollections.order_by('name')
    elif order == 'register_order_des':
        mycollections = mycollections.order_by('-created_at')
    elif order == 'register_order_asc':
        mycollections = mycollections.order_by('created_at')

    # ページネーション
    paginator = Paginator(mycollections, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    favorite_collections_ids = MyCollection.objects.filter(
        id__in=CollectionFavorite.objects.filter(user=request.user).values_list('mycollection', flat=True)
    ).values_list('id', flat=True)

    return render(request, 'home.html', {'form': form, 'page_obj': page_obj, 'favorite_collections_ids': favorite_collections_ids})

@login_required
def collection_register(request):
    if request.method == 'POST':
        uploaded_image = request.FILES.get('image_path')

        if uploaded_image and uploaded_image.name.lower().endswith('.heic'):
            uploaded_image = heic_to_jpeg(uploaded_image)

        form = MyCollectionForm(request.POST, {'image_path': uploaded_image}, user=request.user)
        if form.is_valid():
            mycollection = form.save(commit=False)
            mycollection.user = request.user
            mycollection.save()
            form.save_m2m()
            messages.success(request, 'コレクションが登録されました。')
            return redirect('mycollection:home')
        else:
            print("フォームエラー:", form.errors)
    else:
        form = MyCollectionForm(user=request.user)

    return render(request, 'collection_register.html', {'form': form})

@login_required
def collection_edit(request, pk):
    mycollection = get_object_or_404(MyCollection, pk=pk)
    if request.method == 'POST':
        uploaded_image = request.FILES.get('image_path')

        if uploaded_image and uploaded_image.name.lower().endswith('.heic'):
            uploaded_image = heic_to_jpeg(uploaded_image)

        form = MyCollectionForm(request.POST,  {'image_path': uploaded_image} , user=request.user, instance=mycollection)
        if form.is_valid():
            mycollection = form.save(commit=False)
            mycollection.user = request.user
            mycollection.save()
            form.save_m2m()
            messages.success(request, 'コレクションが編集されました。')
            return redirect('mycollection:home')
    else:
        form = MyCollectionForm(user=request.user , instance=mycollection)

    return  render(request,  'collection_edit.html',  {'form':  form})

# HEICをJPGに変更
def heic_to_jpeg(uploaded_image):
    heif_file = open_heif(uploaded_image)
    image = Image.frombytes(
        heif_file.mode,
        heif_file.size,
        heif_file.data,
        "raw",
        heif_file.mode,
        heif_file.stride
    )

    output_io = io.BytesIO()
    image.save(output_io, format="JPEG")
    output_io.seek(0)

    # Django の InMemoryUploadedFile に変換
    return InMemoryUploadedFile(
        output_io,
        'image',
        uploaded_image.name.replace('.HEIC', '.jpg').replace('.heic', '.jpg'),
        'image/jpeg',
        output_io.getbuffer().nbytes,
        None
    )

@login_required
def collection_delete(request, pk):
    mycollection = get_object_or_404(MyCollection, pk=pk)

    if request.method == 'POST':
        mycollection.delete()
        messages.success(request, 'コレクションが削除されました。')
        return redirect('mycollection:home')

    return redirect('mycollection:home')

@login_required
def collection_category_register(request):
    if request.method == 'POST':
        form = CollectionCategoryForm(request.POST)
        if form.is_valid():
            collection_category = form.save(commit=False)
            collection_category.user = request.user
            collection_category.save()
            messages.success(request, 'カテゴリが登録されました。')
            return redirect('mycollection:collection_category_register')
    else:
        form = CollectionCategoryForm()

    return render(request, 'collection_category_register.html', {'form': form})

@login_required
def collection_tag_register(request):
    if request.method == 'POST':
        form = CollectionTagForm(request.POST)
        if form.is_valid():
            collection_tag = form.save(commit=False)
            collection_tag.user = request.user
            collection_tag.save()
            messages.success(request, 'タグが登録されました。')
            return redirect('mycollection:collection_tag_register')
    else:
        form = CollectionTagForm()

    return render(request, 'collection_tag_register.html', {'form': form})

@login_required
def collection_add_favorite(request):
    if request.method == 'POST':
        form = CollectionFavoriteForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, 'お気に入りに登録されました。')
            return redirect('mycollection:home')
    return redirect('mycollection:home')

@login_required
def collection_remove_favorite(request):
    if request.method == 'POST':
        favorite = CollectionFavorite.objects.get(user=request.user, mycollection=request.POST.get('mycollection'))
        favorite.delete()
        messages.success(request, 'お気に入りが解除されました。')
        return redirect('mycollection:home')
    return redirect('mycollection:home')

@login_required
def collection_favorites(request):
    favorite_mycollections = MyCollection.objects.filter(
        id__in=CollectionFavorite.objects.filter(user=request.user).values_list('mycollection', flat=True)
    )
    # ページネーション
    paginator = Paginator(favorite_mycollections, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'collection_favorites.html', {'page_obj': page_obj})

search_project/mycollection/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MyCollection{% endblock %}</title>

    <link rel="icon" type="image/x-icon" href="{% static 'images/collog_favicon.ico' %}">
    <!-- Apple ホームアイコン -->
    <link rel="apple-touch-icon" sizes="180x180"  href="{% static 'images/collog.png' %}" />
    <!-- Android ホームアイコン -->
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'images/collog.png' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <style>
        body {
            background-color: #f8f9fa;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .sidebar {
            background-color: #343a40;
            color: white;
            position: fixed;
            top: 0;
            left: 0;
            height: 100vh;
            width: 220px;
            padding: 20px;
            z-index: 1000;
        }
        .sidebar h3 {
            margin-bottom: 0;
        }
        .sidebar h3 i {
            margin-right: 10px;
            color: white;
        }
        .sidebar a {
            color: white;
            text-decoration: none;
            display: block;
            padding: 10px;
            border-bottom: 2px solid #495057;
            font-size: 1em;
        }
        .sidebar a:hover {
            background-color: #495057;
        }
        .sidebar i {
            margin-right: 10px;
        }
        .sidebar-footer {
            position: absolute;
            bottom: 20px;
            width: calc(100% - 40px);
        }
        .mobile-header {
            display: none;
        }
        .app-logo a {
            padding: 0;
            margin-bottom: 20px;
        }
        .app-logo img {
            width: 100%;
            height: auto;
        }
        @media (max-width: 768px) {
            .sidebar {
                display: none;
            }
            .mobile-header {
                display: block;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                background: #343a40;
                z-index: 1000;
            }
            .navbar-nav a {
                color: white;
                border-bottom: 2px solid #495057;
            }
            .navbar-nav a:hover {
                background-color: #495057;
            }
            .navbar-nav i {
                margin: 10px;
            }
            .app-logo img {
                height: 45px;
                width: auto;
                padding: 2px 10px;
            }
        }
    </style>
</head>
<body>
    <div class="sidebar col-2">
        <div class="app-logo">
            <a href="{% url 'mycollection:home' %}">
                <img src="{% static 'images/collog_yoko.png' %}" alt="アプリロゴ">
            </a>
        </div>
        <a href="{% url 'mycollection:home' %}">コレクション一覧</a>
        <a href="{% url 'mycollection:collection_favorites' %}"><i class="fas fa-star"></i>お気に入り</a>
        <a href="{% url 'mycollection:collection_register' %}"><i class="fas fa-bookmark"></i>コレクション登録</a>
        <a href="{% url 'mycollection:collection_category_register' %}"><i class="fas fa-folder-plus"></i>カテゴリ登録</a>
        <a href="{% url 'mycollection:collection_tag_register' %}"><i class="fas fa-tags"></i>タグ登録</a>

        <div class="sidebar-footer">
            <a>
                <i class="bi bi-person-circle"></i>
                {% if user.is_authenticated %}
                    {{ user.username }}
                {% endif %}
            </a>
            <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fas fa-sign-out-alt"></i>ログアウト</a>
            <form id="logout-form" method="post" action="{% url 'accounts:logout' %}" style="display: none;">
                {% csrf_token %}
            </form>
        </div>
    </div>
    {% block content %}
    {% endblock %}
    <!-- スマホサイズの時のナビゲーションバー -->
    <nav class="navbar mobile-header">
        <div class="row">
            <div class="col-9 d-flex justify-content-start align-items-center home-header">
                <div class="app-logo">
                    <a href="{% url 'mycollection:home' %}">
                        <img src="{% static 'images/collog_yoko.png' %}" alt="アプリロゴ">
                    </a>
                </div>
            </div>
            <div class="col-3 d-flex justify-content-end align-items-center header-home-account">
                <div class="header-hamburger-menu mx-3">
                    <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="スマホサイズ切り替え">
                        <i class="bi bi-list fs-3"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="Navbar">
        <ul class="navbar-nav m-3">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mycollection:home' %}">コレクション一覧</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mycollection:collection_favorites' %}"><i class="fas fa-star"></i>お気に入り</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mycollection:collection_register' %}"><i class="fas fa-bookmark"></i>コレクション登録</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mycollection:collection_category_register' %}"><i class="fas fa-folder-plus"></i>カテゴリ登録</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mycollection:collection_tag_register' %}"><i class="fas fa-tags"></i>タグ登録</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="bi bi-person-circle"></i>
                    {% if user.is_authenticated %}
                        {{ user.username }}
                    {% endif %}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" onclick="event.preventDefault(); document.getElementById('logout-mobile-form').submit();">
                    <i class="fas fa-sign-out-alt"></i>ログアウト
                </a>
                <form id="logout-mobile-form" method="post" action="{% url 'accounts:logout' %}" style="display: none;">
                    {% csrf_token %}
                </form>
            </li>
        </ul>
        </div>
    </nav>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
</body>
</html>

search_project/mycollection/templates/collection_category_register.html
{% extends "base.html" %}

{% block title %}コレクションカテゴリ登録{% endblock %}

{% block content %}
<div class="content col-10">
    <div class="d-flex">
        <div class="row">
            <div class="col-12 col-md-9">
                <div class="row">
                    <div class="col-6">
                        <h4>カテゴリ登録</h4>
                    </div>
                </div>
                <div class="col-12">
                    {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-9">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table">
                        <tbody>
                            <tr>
                                <th><label for="{{ form.name.id_for_label }}">カテゴリ名</label></th>
                                <td>{{ form.name }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="d-grid gap-2 col-6 mx-auto mt-2">
                        <button class="btn form-control" type="submit" style="background-color: #495057; color: #ffffff;">登録</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<style>
    .content {
        margin-left: 240px;
        padding: 20px;
        width: 100%;
    }
    h4 {
        font-weight: bold;
    }
    table {
        border-collapse:separate;
        border-spacing:0 15px;
        border: none;
    }
    table td {
        vertical-align: middle;
        border-bottom: none !important;
    }
    table th {
        vertical-align: middle;
        border-left: 5px solid #495057;
        border-bottom: none !important;
        padding-left: 12px !important;
    }
    .alert {
        margin-bottom: 0;
    }
    @media (max-width: 768px) {
        .content {
            margin-left: 0;
            margin-top: 56px;
        }
    }
</style>
<script type="text/javascript">
    setTimeout(function() {
        let messages = document.querySelector('.messages');
        if (messages) {
        messages.style.display = 'none';
        }
    }, 5000);

    setTimeout(function() {
        let mobile_messages = document.querySelector('.mobile-messages');
        if (mobile_messages) {
            mobile_messages.style.display = 'none';
        }
    }, 5000);
</script>
{% endblock %}

search_project/mycollection/templates/collection_edit.html
{% extends "base.html" %}

{% block title %}コレクション編集{% endblock %}

{% block content %}
<div class="content col-10">
    <div class="d-flex">
        <div class="row">
            <div class="col-12 col-md-9">
                <div class="row">
                    <div class="col-6">
                        <h4>コレクション編集</h3>
                    </div>
                </div>
                <div class="col-6">
                    {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-9">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table">
                        <tbody>
                            <tr>
                                <th><label for="{{ form.name.id_for_label }}">コレクション名</label></th>
                                <td>{{ form.name }}</td>
                            </tr>
                            <tr>
                                <th><label for="{{ form.description.id_for_label }}">説明</label></th>
                                <td>{{ form.description }}</td>
                            </tr>
                            <tr>
                                <th><label for="{{ form.get_date.id_for_label }}">入手日</label></th>
                                <td>{{ form.get_date }}</td>
                            </tr>
                            <tr>
                                <th><label for="{{ form.price.id_for_label }}">価格</label></th>
                                <td>{{ form.price }}</td>
                            </tr>
                            <th><label for="{{ form.collection_category.id_for_label }}">カテゴリ</label></th>
                            <td>{{ form.collection_category }}</td>
                            <tr>
                                <th><label for="{{ form.image_path.id_for_label }}">イメージ画像</label></th>
                                <td>
                                    {{ form.image_path }}
                                    {% if form.instance.image_path %}
                                        <div class="p-3" style="text-align: center;">
                                            <p style="margin-bottom: 0;">現在のイメージ画像</p>
                                            <img src="{{ form.instance.image_path.url }}" alt="現在の画像" class="preview-image">
                                        </div>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <th><label for="{{ form.tag.id_for_label }}">タグ付け</label></th>
                                <td>{{ form.tag }}</td>
                            </tr>
                            <tr>
                                <th><label for="{{ form.memo.id_for_label }}">メモ</label></th>
                                <td>{{ form.memo }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="d-grid gap-2 col-6 mx-auto mt-2">
                        <button class="btn form-control" type="submit" style="background-color: #495057; color: #ffffff;">更新</button>
                    </div>
                </form>
                <div class="d-grid gap-2 col-6 mx-auto mt-2">
                    <form action="{% url 'mycollection:collection_delete' form.instance.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn form-control btn-danger" onclick="return confirm('本当に削除しますか？');">削除</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .content {
        margin-left: 240px;
        padding: 20px;
        width: 100%;
    }
    h4 {
        font-weight: bold;
    }
    table {
        border-collapse:separate;
        border-spacing:0 15px;
        border: none;
    }
    table td {
        vertical-align: middle;
        border-bottom: none !important;
    }
    table th {
        vertical-align: middle;
        border-left: 5px solid #495057;
        border-bottom: none !important;
        padding-left: 12px !important;
    }
    .preview-image {
        max-width: 200px;
    }
    .tag-checkbox-group {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
        width: 100%;
    }
    .tag-checkbox-group input {
        margin-right: 5px;
    }

    .tag-checkbox-group label {
        display: flex;
        align-items: center;
        white-space: nowrap;
    }
    @media (max-width: 768px) {
        .content {
            margin-left: 0;
            margin-top: 56px;
        }
        .preview-image {
            max-width: 150px;
        }
    }
</style>
{% endblock %}